# Generated by Django 4.1.3 on 2023-04-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_item_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('NEW', 'new'), ('USED', 'used')], default='NEW', max_length=4),
        ),
    ]
