# Generated by Django 4.1.3 on 2023-04-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_item_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.CharField(default='No details available.', max_length=600),
        ),
    ]
